name: Check Source Code
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Check Source Code
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/setup-node@v4
