version: 2

updates:
  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: "weekly"
      timezone: "Asia/Tokyo"
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
