name: Check All
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Check All
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: actions/checkout@v4
      - name: Install dependencies
        shell: bash
        run: yarn install --frozen-lockfile
      - name: Formatter & Lint & Type check & Test
        shell: bash
        run: |
          yarn format
