name: Run test
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Run test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: actions/checkout@v3
      - name: Install dependencies
        shell: bash
        run: yarn install --frozen-lockfile
      - name: Test
        shell: bash
        run: |
          yarn format:check
          yarn lint:check
          yarn tsc
          yarn test
